# Copyright Allo authors. All Rights Reserved.
# SPDX-License-Identifier: Apache-2.0
"""Deterministic FIFO/chain wrappers for explicitly described ready/valid IP."""


def emit_ready_valid_wrapper(module, fifo_ports):
    """Emit a single-clock, non-overlapping transaction adapter.

    Input holding registers decouple FIFO reads from the core's ready signal.
    Both fetched and consumed counts are tracked: prefetch is not completion.
    The core must honor its clock enable and retain valid output under stalls.
    """
    widths = {name: width for name, _, width in module._pins()}
    adapter = module.hls.adapter
    lines = [
        "// Copyright Allo authors. All Rights Reserved.",
        "// SPDX-License-Identifier: Apache-2.0",
        "// Generated by Allo. Do not infer protocols from pin names.",
        "`timescale 1ns / 1ps",
        f"module {module.top} (",
    ]
    declarations = [
        "input wire ap_clk, ap_rst, ap_ce, ap_start, ap_continue",
        "output wire ap_ready, ap_idle, ap_done",
    ]
    for original, port in zip(module.ports, fifo_ports):
        width = widths[original.data]
        direction = "input" if port.dir == "in" else "output"
        reverse = "output" if port.dir == "in" else "input"
        declarations += [
            f"{direction} wire [{width - 1}:0] {port.data}",
            f"{direction} wire {port.valid}",
            f"{reverse} wire {port.ready}",
        ]
    lines += [",\n".join("    " + d for d in declarations), ");"]
    lines += [
        "localparam [1:0] IDLE=0, LAUNCH=1, RUN=2, FINISHED=3;",
        "reg [1:0] state;",
        "wire active = state == RUN;",
        "wire accept = ap_ce && !ap_rst && state == IDLE && ap_start;",
        "wire core_ce = ap_rst || (ap_ce && (state == LAUNCH || active));",
        "assign ap_ready = !ap_rst && ap_ce && state == IDLE;",
        "assign ap_idle = !ap_rst && state == IDLE;",
        "assign ap_done = !ap_rst && state == FINISHED;",
    ]
    core_reset = "ap_rst" if module.reset_active_high else "!ap_rst"
    connections = [
        f".{module.clock}(ap_clk)",
        f".{module.reset}({core_reset})",
        f".{adapter.clock_enable}(core_ce)",
    ]
    if module.start:
        connections.append(f".{module.start}(state == LAUNCH && ap_ce && !ap_rst)")
    if module.done:
        lines.append("wire core_done;")
        connections.append(f".{module.done}(core_done)")
    done_condition = "1'b1"
    if adapter.completion == "done":
        lines += [
            "reg done_seen;",
            "always @(posedge ap_clk) begin",
            "  if (ap_rst) done_seen <= 0;",
            "  else if (ap_ce) begin",
            "    if (accept) done_seen <= 0;",
            "    else if (active && core_done) done_seen <= 1;",
            "  end",
            "end",
        ]
        done_condition = "(done_seen || core_done)"
    completed = []
    for index, (original, port) in enumerate(zip(module.ports, fifo_ports)):
        prefix = f"s{index}"
        width = widths[original.data]
        bits = max(1, port.size.bit_length())
        limit = f"{bits}'d{port.size}"
        lines += [f"reg [{bits - 1}:0] {prefix}_count;"]
        completed.append(f"({prefix}_count == {limit})")
        if port.dir == "in":
            lines += [
                f"reg [{width - 1}:0] {prefix}_data;",
                f"reg {prefix}_valid;",
                f"reg [{bits - 1}:0] {prefix}_fetched;",
                f"wire {prefix}_ready;",
                f"wire {prefix}_fire = active && !ap_rst && ap_ce && {prefix}_valid && {prefix}_ready;",
                f"assign {port.ready} = active && !ap_rst && ap_ce && {port.valid}",
                f"    && {prefix}_fetched < {limit} && (!{prefix}_valid || {prefix}_fire);",
                "always @(posedge ap_clk) begin",
                f"  if (ap_rst) begin {prefix}_count <= 0; {prefix}_fetched <= 0; {prefix}_valid <= 0; {prefix}_data <= 0; end",
                "  else if (ap_ce) begin",
                f"    if (accept) begin {prefix}_count <= 0; {prefix}_fetched <= 0; {prefix}_valid <= 0; end",
                "    else if (active) begin",
                f"      if ({prefix}_fire) begin {prefix}_valid <= 0; {prefix}_count <= {prefix}_count + 1'b1; end",
                f"      if ({port.ready}) begin",
                f"        {prefix}_data <= {port.data}; {prefix}_valid <= 1;",
                f"        {prefix}_fetched <= {prefix}_fetched + 1'b1;",
                "      end",
                "    end",
                "  end",
                "end",
            ]
            connections += [
                f".{original.data}({prefix}_data)",
                f".{original.valid}({prefix}_valid && active && !ap_rst)",
                f".{original.ready}({prefix}_ready)",
            ]
        else:
            lines += [
                f"wire [{width - 1}:0] {prefix}_data;",
                f"wire {prefix}_valid;",
                f"wire {prefix}_ready = active && !ap_rst && ap_ce && {port.ready} && {prefix}_count < {limit};",
                f"assign {port.data} = {prefix}_data;",
                f"assign {port.valid} = {prefix}_valid && {prefix}_ready;",
                "always @(posedge ap_clk) begin",
                f"  if (ap_rst) {prefix}_count <= 0;",
                "  else if (ap_ce) begin",
                f"    if (accept) {prefix}_count <= 0;",
                f"    else if ({port.valid}) {prefix}_count <= {prefix}_count + 1'b1;",
                "  end",
                "end",
            ]
            connections += [
                f".{original.data}({prefix}_data)",
                f".{original.valid}({prefix}_valid)",
                f".{original.ready}({prefix}_ready)",
            ]
    lines += [
        "always @(posedge ap_clk) begin",
        "  if (ap_rst) state <= IDLE;",
        "  else if (ap_ce) begin",
        "    case (state)",
        "      IDLE: if (ap_start) state <= LAUNCH;",
        "      LAUNCH: state <= RUN;",
        f"      RUN: if ({' && '.join(completed)} && {done_condition}) state <= FINISHED;",
        "      FINISHED: if (ap_continue) state <= IDLE;",
        "      default: state <= IDLE;",
        "    endcase",
        "  end",
        "end",
    ]
    parameters = ""
    if module.parameters:
        parameters = (
            " #(\n"
            + ",\n".join(
                f"    .{name}({value})"
                for name, value in sorted(module.parameters.items())
            )
            + "\n)"
        )
    lines += [
        f"{module.rtl_top}{parameters} core (",
        ",\n".join("    " + c for c in connections),
        ");",
        "endmodule",
    ]
    return "\n".join(lines) + "\n"
